baseURL = ""
languageCode = "en-us"
title = "Araw Seekers"
theme = "hello-friend-ng"
publishDir = "docs"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

[params]
  dateform        = "02 Jan 2006"
  dateformShort   = "02 Jan"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  homeSubtitle = "(A)typical Experiences by Photosynthesis"
  keywords = ""
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "🌞 Araw Seekers 🌞"
    subtitle = "(A)typical Experiences by Photosynthesis"
    keywords = ""
    copyright = "Isya and Ohio"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "HOME"
      path = ""
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "ABOUT"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Blog"
        url = "/posts"

#social icons

  [[params.social]]
    name = "email"
    url  = "mailto:arawseekers@tuta.io"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

    [privacy]
      [privacy.disqus]
        disable = true
      [privacy.googleAnalytics]
        disable = true
      [privacy.instagram]
        disable = true
      [privacy.twitter]
        disable = true
      [privacy.vimeo]
        disable = true
      [privacy.youtube]
        disable = true
